### ISSUE TITLE
Extra spaces in conversations

### ISSUE THREAD

**Issue by Danila35** [EverMCServer/vscode-BetonQuest#15]
In versions of betonQuest 3.0.0, the dialogs have been redesigned and now extra spaces in the dialogs prevent using this plugin, if you can somehow solve this, it would be cool.
Here are examples of how it shouldn't be:
```
conversations:
  BlackMarketVendorMalrik:
    quester: Malrik
    first: node_1, node_3
    NPC_options:
      node_1:
        text: ...
        pointers: node_2, node_10
      node_3:
        text: ...
  player_options:
      node_2:
        text: ...
      node_10:
        text: ...
```
And how it should be:

```
conversations:
  BlackMarketVendorMalrik:
    quester: Malrik
    first: node_1,node_3
    NPC_options:
      node_1:
        text: ...
        pointers: node_2,node_10
      node_3:
        text: ...
  player_options:
      node_2:
        text: ...
        events: shop26_1
      node_10:
        text: ...
```
