### ISSUE TITLE
BetonQuest 2.0-DEV file structure support

### ISSUE THREAD

**Issue by Horion6102** [EverMCServer/vscode-BetonQuest#5]
Hi, me and Xenap used your VSCode plugin do write quest in BetonQuest but we have a problem about the format of files conversation ?

With your structure of file conversation we can't link NPC to conversation.

Example :

package.yml
```yml
npcs:
  "13": Maid
```

My files format :
```yml
conversations:
  Maid: # Link for my npc
    quester: Maid
    first: node_1
    stop: "true"
    NPC_options:
      node_1:
        text: test
    player_options: {}
```

Your files format :
```yml
quester: Maid
first: node_1
stop: "true"
NPC_options:
  node_1:
    text: dsq
player_options: {}
```

problem in your format files nothing link npc to conversation 

Files BetonQuest
![image](https://github.com/EverMCServer/vscode-BetonQuest/assets/97897215/aa584e89-6a66-44c5-981b-95f2a6520b89)

Do you use another file structure
